version: '3'
services:
  postgres:
    image: postgres:9
    ports:
      - "15432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      POSTGRES_PASSWORD: postgres
